### ISSUE TITLE
Create a package.json for NPM installation

### ISSUE THREAD

**Issue by dtaylor113** [DataTables/ColVis#43]
Hi,
We use datatables-colvis as a dependency in our PatternFly toolkit (patternfly.org), however some of our consumers only use NPM to install PatternFly, so they currently can not get the datatables-colvis dependency since there isn't currently an official published NPM package for datatables-colvis.

We are planning on publishing an NPM for datatables-colvis, but it would be ideal if there was an official NPM.

Thanks,
Dave Taylor

**Comment by DataTables** [comment]
Hi Dave,

Thanks for bringing this up. ColVis is actually retired software now and is no longer being developed. It has been replaced by the column visibility controls for the [Buttons extension](//datatables.net/extensions/buttons).

If I were to add an NPM package for ColVis it would need to be immediately marked as deprecated. Rather than publish ColVis on NPM I'd rather that Buttons be used, which is already available on NPM (`datatables.net-buttons`).

**Comment by DataTables** [comment]
Nice styling of DataTables in PatternFly btw! Very smart indeed.
